# Generated by Django 5.2.11 on 2026-02-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPGeoCache',
            fields=[
                ('ip', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('country_code', models.CharField(blank=True, default='', max_length=10)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('isp', models.CharField(blank=True, default='', max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ip_geo_cache',
            },
        ),
    ]
