# Generated by Django 5.2.12 on 2026-03-12 02:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_nginxlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Secret returned to JS — used to authenticate ping/end requests.')),
                ('path', models.CharField(max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=512)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen_at', models.DateTimeField()),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False, help_text='True once the end beacon has been received.')),
            ],
        ),
        migrations.RenameIndex(
            model_name='nginxlog',
            new_name='nginx_log_time_9a39a5_idx',
            old_name='nginx_log_time_status_idx',
        ),
        migrations.RenameIndex(
            model_name='nginxlog',
            new_name='nginx_log_ip_3d1063_idx',
            old_name='nginx_log_ip_time_idx',
        ),
        migrations.AddField(
            model_name='pagesession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pagesession',
            index=models.Index(fields=['user', 'started_at'], name='stats_pages_user_id_607c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='pagesession',
            index=models.Index(fields=['path', 'started_at'], name='stats_pages_path_91019f_idx'),
        ),
    ]
