# Generated by Django 5.2.12 on 2026-04-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_savedgraphconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.CharField(blank=True, default='', max_length=45)),
                ('form_data', models.JSONField(help_text='Submitted form fields, passwords excluded.')),
                ('errors', models.JSONField(help_text='Form validation errors.')),
            ],
            options={
                'db_table': 'failed_signup',
                'ordering': ['-attempted_at'],
            },
        ),
    ]
