# Generated by Django 5.2.11 on 2026-02-21 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0019_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.IntegerField(blank=True, help_text='Limit analysis to this report_type. Leave blank to compare all types.', null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='QUEUED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reports_found', models.IntegerField(default=0)),
                ('reports_processed', models.IntegerField(default=0)),
                ('pages_processed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageMatch',
            fields=[
                ('page_match_id', models.AutoField(primary_key=True, serialize=False)),
                ('similarity', models.FloatField()),
            ],
            options={
                'ordering': ['-similarity'],
            },
        ),
        migrations.CreateModel(
            name='ReportChunk',
            fields=[
                ('chunk_id', models.AutoField(primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('text', models.TextField()),
                ('bbox_x0', models.FloatField(blank=True, null=True)),
                ('bbox_y0', models.FloatField(blank=True, null=True)),
                ('bbox_x1', models.FloatField(blank=True, null=True)),
                ('bbox_y1', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['page', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='ChunkMatch',
            fields=[
                ('chunk_match_id', models.AutoField(primary_key=True, serialize=False)),
                ('similarity', models.FloatField()),
                ('page_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_matches', to='reports.pagematch')),
                ('chunk_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to='reports.reportchunk')),
                ('chunk_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to='reports.reportchunk')),
            ],
            options={
                'ordering': ['-similarity'],
            },
        ),
        migrations.CreateModel(
            name='ReportPage',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_number', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='events.report')),
            ],
            options={
                'ordering': ['report', 'page_number'],
            },
        ),
        migrations.AddField(
            model_name='reportchunk',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='reports.reportpage'),
        ),
        migrations.AddField(
            model_name='pagematch',
            name='page_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to='reports.reportpage'),
        ),
        migrations.AddField(
            model_name='pagematch',
            name='page_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to='reports.reportpage'),
        ),
        migrations.AddIndex(
            model_name='reportpage',
            index=models.Index(fields=['report', 'page_number'], name='reports_rep_report__ce1dde_idx'),
        ),
        migrations.AddIndex(
            model_name='pagematch',
            index=models.Index(fields=['-similarity'], name='reports_pag_similar_f23db2_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagematch',
            constraint=models.UniqueConstraint(fields=('page_a', 'page_b'), name='uniq_page_match'),
        ),
    ]
