# Generated by Django 5.2.11 on 2026-02-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportimage_imagematch_analysisjob_images_processed'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='imagematch',
            new_name='reports_ima_hamming_52e280_idx',
            old_name='reports_ima_hamming_idx',
        ),
        migrations.RenameIndex(
            model_name='reportimage',
            new_name='reports_rep_report__f34143_idx',
            old_name='reports_rep_report__img_idx',
        ),
    ]
