# Generated by Django 5.2.11 on 2026-02-22 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_report_released'),
        ('reports', '0005_analysisJob_similarity_jobtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Limit AI detection to this event (required for AI_DETECTION jobs).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_detection_jobs', to='events.event'),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='job_type',
            field=models.CharField(choices=[('EXTRACTION', 'Extraction'), ('SIMILARITY', 'Similarity Analysis'), ('FULL', 'Full Analysis'), ('AI_DETECTION', 'AI Detection')], default='FULL', max_length=16),
        ),
        migrations.CreateModel(
            name='AIDetectionResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('fake_percentage', models.FloatField()),
                ('ai_words', models.IntegerField(default=0)),
                ('text_words', models.IntegerField(default=0)),
                ('h_score', models.FloatField(blank=True, null=True)),
                ('collection_id', models.CharField(blank=True, max_length=255)),
                ('zerogpt_id', models.CharField(blank=True, max_length=255)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_detection', to='reports.reportpage')),
            ],
            options={
                'ordering': ['page'],
            },
        ),
        migrations.CreateModel(
            name='AIDetectedSentence',
            fields=[
                ('sentence_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentence_index', models.IntegerField()),
                ('text', models.TextField()),
                ('generated_probability', models.FloatField(blank=True, null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='reports.aidetectionresult')),
            ],
            options={
                'ordering': ['result', 'sentence_index'],
            },
        ),
    ]
