# Generated by Django 5.2.13 on 2026-04-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_analysisjob_can_run_ai_detection_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='export_file',
            field=models.CharField(blank=True, help_text='S3 key of the generated export file (ZIP).', max_length=255),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='job_type',
            field=models.CharField(choices=[('EXTRACTION', 'Extraction'), ('SIMILARITY', 'Similarity Analysis'), ('FULL', 'Full Analysis'), ('AI_DETECTION', 'AI Detection'), ('BULK_PDF_EXPORT', 'Bulk PDF Export')], default='FULL', max_length=16),
        ),
    ]
