# Generated by Django 5.2.12 on 2026-03-20 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='crowdsubmission',
            new_name='engagement__status_833a9d_idx',
            old_name='engagement__status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='fanvote',
            new_name='engagement__categor_0e0e54_idx',
            old_name='engagement__fanvote_cat_team_idx',
        ),
    ]
