"""
Django settings for iqs_site project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import yaml

def env_bool(name: str, default: bool = False) -> bool:
    val = os.environ.get(name)
    if val is None:
        return default
    return val.strip().lower() in ("1", "true", "yes", "on")

def env_list(name: str, default: list[str] | None = None) -> list[str]:
    val = os.environ.get(name)
    if not val:
        return default or []
    return [x.strip() for x in val.split(",") if x.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOGGING_DIR =Path("/var/www/quarterscale/")
SITE_VARIANT = os.environ.get("SITE_VARIANT","normal")
print(f"Starting server with site variant: {SITE_VARIANT}")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

with open(BASE_DIR / "site_config.yaml") as f:
    ALL_CONFIG=yaml.safe_load(f)

SITE_CONFIG=ALL_CONFIG[SITE_VARIANT]

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-ne&$^!n&q^@6eq7sm_+c@j!n34nbnbzcf58i-_&i@h1#4hozml'
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]  # hard fail if missing

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = SITE_CONFIG["DEBUG"]
DEBUG = env_bool("DJANGO_DEBUG", default=bool(SITE_CONFIG.get("DEBUG", False)))

# ALLOWED_HOSTS = [
#     "38.22.155.20",
#     "internationalquarterscale.com",
#     "www.internationalquarterscale.com",
#     "testing.internationalquarterscale.com",
#     "localhost",
#     "127.0.0.1",
# ]

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    default=[
        "38.22.155.20",
        "internationalquarterscale.com",
        "www.internationalquarterscale.com",
        "testing.internationalquarterscale.com",
        "localhost",
        "127.0.0.1",
    ],
)
#ALLOWED_HOSTS=["192.168.3.100","127.0.0.1"]

STATICFILES_DIRS = []
# Application definition

STATIC_ROOT = "/var/www/quarterscale/static/"

from pathlib import Path

MEDIA_BASE_DIR = Path("/var/www/quarterscale")

# STATIC_URL = "/static/"
# STATIC_ROOT = BASE_DIR / "staticfiles"   # collectstatic output (prod)

MEDIA_URL = "/media/"
MEDIA_ROOT = MEDIA_BASE_DIR/"static"          # uploaded photos/live media

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    "corsheaders",
    'events',
    'live',
    "techin",
    "users",
    "stats",
    "django_celery_beat",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    
]

# CORS_ALLOWED_ORIGINS = [
#     "https://www.internationalquarterscale.com",
#     "https://testing.internationalquarterscale.com",
#     "http://127.0.0.1:9000",
#     "https://api.internationalquarterscale.com"
# ]

CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "https://www.internationalquarterscale.com",
        "https://testing.internationalquarterscale.com",
        "http://127.0.0.1:9000",
        "https://api.internationalquarterscale.com",
        "https://api.iqsconnect.org",
        "https://iqsconnect.org"
        
    ],
)

CSRF_TRUSTED_ORIGINS = [
    "https://testing.internationalquarterscale.com",
    "https://internationalquarterscale.com",
    "https://iqsconnect.org"
    # add others if you post from them, e.g.
    # "https://internationalquarterscale.com",
]



ROOT_URLCONF = 'iqs_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iqs_site.wsgi.application'

SITE_ID = 1
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": SITE_CONFIG["DB_NAME"],
#         "USER": SITE_CONFIG["DB_USER"],
#         "PASSWORD": SITE_CONFIG["DB_PASSWORD"],
#         "HOST": SITE_CONFIG["DB_HOST"],    
#         "PORT": SITE_CONFIG["DB_PORT"],         
#         "OPTIONS": {
#             "charset": "utf8mb4",
#             "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }

DB_NAME = os.environ["DB_NAME"]
DB_USER = os.environ["DB_USER"]
DB_PASSWORD = os.environ["DB_PASSWORD"]
DB_HOST = os.environ["DB_HOST"]
DB_PORT = os.environ["DB_PORT"]



DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

if not DEBUG:
    for k in ("DB_NAME", "DB_USER", "DB_PASSWORD", "DB_HOST"):
        if not os.environ.get(k):
            raise RuntimeError(f"Missing required env var: {k}")



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

from django.conf import settings

if getattr(settings, "SITE_VARIANT", "normal") == "testing":
    root_prefix = "testing"   
else:
    root_prefix = ""  

LOGIN_REDIRECT_URL = "users:account"
LOGOUT_REDIRECT_URL = "events:landing"
LOGIN_URL = "login"

#EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    # ---- Where logs go ----
    "handlers": {
        # "file_500": {
        #     "level": "ERROR",
        #     "class": "logging.FileHandler",
        #     "filename": os.path.join(LOGGING_DIR, "logs",SITE_VARIANT,"django_500.log"),
        # },
        "console": {
            "class": "logging.StreamHandler",
        },
    },

    # ---- What logging events should use those handlers ----
    "loggers": {
        # Django internal errors (including 500s)
        "django.request": {
            "handlers": [ "console"],
            "level": "ERROR",
            "propagate": False,
        },

        # Optional: log template errors, email errors, etc.
        "django.server": {
            "handlers": [ "console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

REDIS_URL = os.environ.get("REDIS_URL", "redis://redis:6379/1")
REDIS_KEY_PREFIX = os.environ.get("REDIS_KEY_PREFIX", "iqs")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": REDIS_KEY_PREFIX,
        "TIMEOUT": int(os.environ.get("REDIS_DEFAULT_TIMEOUT", "60")),
    }
}

if DEBUG:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        }
    }


# Email via Gmail SMTP
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False



# EMAIL_HOST_USER = SITE_CONFIG["EMAIL_HOST_USER"]
# EMAIL_HOST_PASSWORD = SITE_CONFIG["EMAIL_HOST_PASSWORD"]

# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# SERVER_EMAIL = EMAIL_HOST_USER  # for error emails, if you use AdminEmailHandler

EMAIL_HOST_USER = os.environ["EMAIL_HOST_USER"]
EMAIL_HOST_PASSWORD = os.environ["EMAIL_HOST_PASSWORD"]

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
SERVER_EMAIL = os.environ.get("SERVER_EMAIL", EMAIL_HOST_USER)

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", REDIS_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
