"""
Django settings for iqs_site project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import yaml

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOGGING_DIR =Path("/var/www/quarterscale/")
SITE_VARIANT = os.environ.get("SITE_VARIANT","normal")
print(f"Starting server with site variant: {SITE_VARIANT}")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

with open(BASE_DIR / "site_config.yaml") as f:
    ALL_CONFIG=yaml.safe_load(f)

SITE_CONFIG=ALL_CONFIG[SITE_VARIANT]

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ne&$^!n&q^@6eq7sm_+c@j!n34nbnbzcf58i-_&i@h1#4hozml'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = SITE_CONFIG["DEBUG"]

ALLOWED_HOSTS = ["internationalquarterscale.com","127.0.0.1"]

STATICFILES_DIRS = []
# Application definition

STATIC_ROOT = "/var/www/quarterscale/static/"

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'events',
    'live',
    "techin",
    "users",
    "stats"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iqs_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iqs_site.wsgi.application'

SITE_ID = 1
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": SITE_CONFIG["DB_NAME"],
        "USER": SITE_CONFIG["DB_USER"],
        "PASSWORD": SITE_CONFIG["DB_PASSWORD"],
        "HOST": SITE_CONFIG["DB_HOST"],    
        "PORT": SITE_CONFIG["DB_PORT"],         
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

from django.conf import settings

if getattr(settings, "SITE_VARIANT", "normal") == "testing":
    root_prefix = "testing"   
else:
    root_prefix = ""  

LOGIN_REDIRECT_URL = "users:account"
LOGOUT_REDIRECT_URL = "events:landing"
LOGIN_URL = "login"

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    # ---- Where logs go ----
    "handlers": {
        # "file_500": {
        #     "level": "ERROR",
        #     "class": "logging.FileHandler",
        #     "filename": os.path.join(LOGGING_DIR, "logs",SITE_VARIANT,"django_500.log"),
        # },
        "console": {
            "class": "logging.StreamHandler",
        },
    },

    # ---- What logging events should use those handlers ----
    "loggers": {
        # Django internal errors (including 500s)
        "django.request": {
            "handlers": [ "console"],
            "level": "ERROR",
            "propagate": False,
        },

        # Optional: log template errors, email errors, etc.
        "django.server": {
            "handlers": [ "console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # use db 1 (0 is fine too)
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": "iqs",  # important if you have testing/prod on same redis
        "TIMEOUT": 60,        # default TTL seconds (override per-call as needed)
    }
}