# Generated by Django 6.0 on 2025-12-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTractorRuleStatus',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'event_tractor_rule_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('rule_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('rule_content', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'rules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RuleCategory',
            fields=[
                ('rule_catagory_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('rule_catagory_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rule_catagories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RuleSubCategory',
            fields=[
                ('rule_subcatagory_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('rule_subcatagory_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rule_sub_catagories',
                'managed': False,
            },
        ),
    ]
