# Generated by Django 6.0 on 2025-12-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rulesubcategory',
            table='rule_subcatagories',
        ),
    ]
