# Generated by Django 6.0 on 2025-12-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techin', '0002_alter_rulesubcategory_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rulecategory',
            table='rule_categories',
        ),
        migrations.AlterModelTable(
            name='rulesubcategory',
            table='rule_subcategories',
        ),
    ]
