# Generated by Django 5.2.10 on 2026-01-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techin', '0003_alter_rulecategory_table_alter_rulesubcategory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleTractorMedia',
            fields=[
                ('id', models.AutoField(db_column='rule_tractor_media_id', primary_key=True, serialize=False)),
                ('media_type', models.IntegerField(choices=[(1, 'Youtube Video'), (2, 'Image'), (3, 'Comment')])),
                ('media', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'rule_tractor_media',
                'managed': False,
            },
        ),
    ]
