# Generated by Django 5.2.11 on 2026-02-27 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0021_move_schedule_models_to_schedule_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardType',
            fields=[
                ('award_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='awards/')),
                ('category', models.CharField(choices=[('REPORT', 'Report'), ('PRESENTATION', 'Presentation'), ('PULL', 'Pull'), ('OVERALL', 'Overall'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('award_id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('display_order', models.IntegerField(default=0)),
                ('event_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='events.eventteam')),
                ('award_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='awards.awardtype')),
            ],
            options={
                'ordering': ['event_team__event__event_datetime', 'display_order'],
                'unique_together': {('award_type', 'event_team')},
            },
        ),
    ]
