# Generated by Django 5.2.11 on 2026-03-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['event_team__event__event_datetime', 'award_type__display_order', 'placement']},
        ),
        migrations.AddField(
            model_name='award',
            name='placement',
            field=models.IntegerField(blank=True, choices=[(1, '1st Place'), (2, '2nd Place'), (3, '3rd Place')], null=True),
        ),
    ]
