# Generated by Django 5.2.11 on 2026-03-01 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_alter_award_options_award_placement'),
        ('events', '0021_move_schedule_models_to_schedule_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardtype',
            name='team_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_types', to='events.teamclass'),
        ),
    ]
