# Generated by Django 6.0 on 2025-12-04 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTeam',
            fields=[
                ('event_team_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event_teams',
                'ordering': ['-total_score'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventTeamPhoto',
            fields=[
                ('event_team_photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_from_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_path', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('approved', models.BooleanField()),
            ],
            options={
                'db_table': 'event_team_photos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PullData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('chain_force', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pull_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamClass',
            fields=[
                ('team_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'team_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('tractor_id', models.AutoField(primary_key=True, serialize=False)),
                ('tractor_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tractors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TractorEvent',
            fields=[
                ('tractor_event_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tractor_events',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hook',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pull',
            options={'managed': False, 'ordering': ['-final_distance']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'managed': False},
        ),
    ]
