# Generated by Django 6.0 on 2025-12-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventteam_eventteamphoto_pulldata_teamclass_tractor_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.AlterModelTable(
            name='hook',
            table='hooks',
        ),
        migrations.AlterModelTable(
            name='pull',
            table='pulls',
        ),
        migrations.AlterModelTable(
            name='team',
            table='teams',
        ),
    ]
