# Generated by Django 6.0 on 2025-12-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_table_alter_hook_table_alter_pull_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullMedia',
            fields=[
                ('pull_media_id', models.AutoField(primary_key=True, serialize=False)),
                ('pull_media_type', models.IntegerField(choices=[(1, 'Youtube Video'), (2, 'Image')])),
                ('link', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pull_media',
                'managed': False,
            },
        ),
    ]
