# Generated by Django 5.2.10 on 2026-01-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_pullmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('schedule_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'schedule_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleItemType',
            fields=[
                ('schedule_item_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'schedule_item_types',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='eventteamphoto',
            options={'managed': False, 'permissions': [('can_auto_approve_team_photos', 'Can auto-approve uploaded team photos')]},
        ),
    ]
