# Generated by Django 5.2.10 on 2026-01-29 02:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_fix_event_pk_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurabilityRun',
            fields=[
                ('durability_run_id', models.AutoField(primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, help_text='1 for the first attempt; increment for re-runs.', validators=[django.core.validators.MinValueValidator(1)])),
                ('final_lap_count', models.PositiveSmallIntegerField(blank=True, help_text='Total completed laps. Leave blank until the run is finished.', null=True)),
                ('final_time', models.DurationField(blank=True, help_text='Elapsed time for the run (hh:mm:ss). Leave blank until finished.', null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('dnf', 'DNF'), ('dns', 'DNS'), ('dsq', 'DSQ')], default='completed', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(db_column='event_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='durability_runs', to='events.event')),
                ('team', models.ForeignKey(db_column='team_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='durability_runs', to='events.team')),
                ('tractor', models.ForeignKey(db_column='tractor_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='durability_runs', to='events.tractor')),
            ],
            options={
                'db_table': 'durability_runs',
                'managed': True,
                'indexes': [models.Index(fields=['event', 'status'], name='durability__event_i_739332_idx'), models.Index(fields=['event', 'team'], name='durability__event_i_146e3e_idx'), models.Index(fields=['event', 'tractor'], name='durability__event_i_28bfd5_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'team', 'tractor', 'attempt_number'), name='uniq_dur_run_event_team_tractor_attempt')],
            },
        ),
    ]
