# Generated by Django 5.2.10 on 2026-01-31 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_durabilityrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurabilityData',
            fields=[
                ('durability_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('speed', models.FloatField()),
                ('pressure', models.FloatField()),
                ('power', models.FloatField()),
                ('durability_run', models.ForeignKey(db_column='durability_run_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='data', to='events.durabilityrun')),
            ],
            options={
                'db_table': 'durability_data',
                'managed': True,
            },
        ),
    ]
