# Generated by Codex on 2026-02-08

from django.db import migrations, models


def copy_pull_media(apps, schema_editor):
    from django.db import connection

    with connection.cursor() as cursor:
        # Check pull_media table and pull_id column both exist
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.columns "
            "WHERE table_schema = DATABASE() AND table_name = 'pull_media' "
            "AND column_name = 'pull_id'"
        )
        if cursor.fetchone()[0] == 0:
            return

        cursor.execute(
            "INSERT INTO performance_event_media "
            "  (performance_event_id, performance_event_type, media_type, link) "
            "SELECT pull_id, 1, pull_media_type, link "
            "FROM pull_media "
            "WHERE pull_id IS NOT NULL"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_durabilitydata"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceEventMedia",
            fields=[
                ("media_id", models.AutoField(primary_key=True, serialize=False)),
                ("media_type", models.IntegerField(blank=True, null=True)),
                ("link", models.CharField(blank=True, max_length=255, null=True)),
                ("performance_event_id", models.IntegerField(blank=True, null=True)),
                ("performance_event_type", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "performance_event_media",
                "managed": True,
            },
        ),
        migrations.RunPython(copy_pull_media, migrations.RunPython.noop),
    ]
