# Generated by Codex on 2026-02-08

from django.db import migrations, models


def copy_pull_media(apps, schema_editor):
    PullMedia = apps.get_model("events", "PullMedia")
    PerformanceEventMedia = apps.get_model("events", "PerformanceEventMedia")

    rows = PullMedia.objects.all().values(
        "pull_id",
        "pull_media_type",
        "link",
    )

    to_create = []
    for row in rows:
        to_create.append(
            PerformanceEventMedia(
                performance_event_id=row["pull_id"],
                performance_event_type=1,
                media_type=row["pull_media_type"],
                link=row["link"],
            )
        )

    if to_create:
        PerformanceEventMedia.objects.bulk_create(to_create, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_durabilitydata"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceEventMedia",
            fields=[
                ("media_id", models.AutoField(primary_key=True, serialize=False)),
                ("media_type", models.IntegerField(blank=True, null=True)),
                ("link", models.CharField(blank=True, max_length=255, null=True)),
                ("performance_event_id", models.IntegerField(blank=True, null=True)),
                ("performance_event_type", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "performance_event_media",
                "managed": True,
            },
        ),
        migrations.RunPython(copy_pull_media, migrations.RunPython.noop),
    ]
