# Generated by Django 5.2.11 on 2026-02-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_performance_media_and_durability_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManeuverabilityRun',
            fields=[
                ('maneuverability_run_id', models.AutoField(primary_key=True, serialize=False)),
                ('run_order', models.IntegerField()),
                ('state', models.CharField(default='SCHEDULED', max_length=24)),
                ('updated_at', models.DateTimeField()),
                ('updated_by_source', models.CharField(default='system', max_length=16)),
            ],
            options={
                'db_table': 'maneuverability_runs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('team_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('info_type', models.IntegerField(choices=[(1, 'Instagram'), (2, 'Facebook'), (3, 'Website'), (4, 'Bio'), (5, 'Nickname'), (6, 'Youtube'), (7, 'Linkedin')])),
                ('info', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'team_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TractorInfo',
            fields=[
                ('tractor_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('info_type', models.IntegerField(choices=[(1, 'Instagram'), (2, 'Facebook'), (3, 'Website'), (4, 'Bio'), (5, 'Nickname'), (6, 'Youtube'), (7, 'Linkedin')])),
                ('info', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tractor_info',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='durabilitydata',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='durabilityrun',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='performanceeventmedia',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='scorecategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='scorecategoryinstance',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='scoresubcategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='scoresubcategoryinstance',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='scoresubcategoryscore',
            options={'managed': False},
        ),
    ]
