# Generated by Django 5.2.11 on 2026-02-11 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_performanceeventmedia_options_editlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editlog',
            name='team',
            field=models.ForeignKey(blank=True, db_column='team_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_logs', to='events.team'),
        ),
        migrations.AlterField(
            model_name='editlog',
            name='tractor',
            field=models.ForeignKey(blank=True, db_column='tractor_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_logs', to='events.tractor'),
        ),
    ]
