# Generated by Django 5.2.11 on 2026-02-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_eventteamphoto_official'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullExportJob',
            fields=[
                ('pull_export_job_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired')], max_length=20)),
                ('filters_json', models.TextField(blank=True, null=True)),
                ('total_pulls', models.IntegerField(blank=True, null=True)),
                ('processed_pulls', models.IntegerField(blank=True, null=True)),
                ('zip_rel_path', models.CharField(blank=True, max_length=255, null=True)),
                ('download_url', models.CharField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pull_export_jobs',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PullExportJobItem',
            fields=[
                ('pull_export_job_item_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pull_export_job_items',
                'managed': False,
            },
        ),
    ]
