# Generated by Django 5.2.11 on 2026-02-14 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_pullexportjob_pullexportjobitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.IntegerField()),
                ('report_link', models.CharField(max_length=255)),
                ('event_team', models.ForeignKey(db_column='event_team_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports', to='events.eventteam')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
