# Generated by Django 5.2.11 on 2026-02-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='released',
            field=models.BooleanField(default=False),
        ),
    ]
