# Generated by Django 5.2.11 on 2026-03-06 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_move_schedule_models_to_schedule_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'managed': False, 'permissions': [('can_edit_any_team', 'Can edit any team')]},
        ),
    ]
