# Generated by Django 5.2.12 on 2026-03-26 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorecategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='scorecategoryinstance',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='scoresubcategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='scoresubcategoryinstance',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='scoresubcategoryscore',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='ScoreCategoryScore',
            fields=[
                ('score_category_score_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('category_instance', models.ForeignKey(db_column='category_instance_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_scores', to='events.scorecategoryinstance')),
                ('team', models.ForeignKey(db_column='team_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_scores', to='events.team')),
            ],
            options={
                'db_table': 'score_category_scores',
                'managed': True,
                'unique_together': {('team', 'category_instance')},
            },
        ),
    ]
