# Generated by Django 5.2.12 on 2026-03-26 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_scorecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecategoryinstance',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresubcategoryinstance',
            name='category_instance',
            field=models.ForeignKey(blank=True, db_column='category_instance_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcategory_instances', to='events.scorecategoryinstance'),
        ),
        migrations.AddField(
            model_name='scoresubcategoryscore',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
