# Generated by Django 5.2.13 on 2026-06-27 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_maneuverabilityrun_score'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='enginedata',
            new_name='engine_data_pull_id_622deb_idx',
            old_name='engine_data_pull_id_idx',
        ),
        migrations.RenameIndex(
            model_name='enginedata',
            new_name='engine_data_durabil_944c78_idx',
            old_name='engine_data_dur_run_idx',
        ),
    ]
