# Generated by Django 5.2.12 on 2026-03-12 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compforms', '0002_seed_questions'),
        ('events', '0022_alter_team_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('num_assigned', models.PositiveIntegerField(default=0, help_text='Questions randomly assigned per team. 0 = show all.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Shared namespace with FormQuestion.order — controls interleave order on form.')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='compforms.compform')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('form', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GroupQuestion',
            fields=[
                ('group_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_questions', to='compforms.question')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_questions', to='compforms.questiongroup')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('group', 'question')},
            },
        ),
        migrations.CreateModel(
            name='TeamQuestionAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_order', models.PositiveIntegerField()),
                ('event_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_assignments', to='events.eventteam')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='compforms.questiongroup')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='compforms.question')),
            ],
            options={
                'ordering': ['group', 'display_order'],
                'indexes': [models.Index(fields=['event_team', 'group'], name='compforms_t_event_t_f60545_idx')],
                'unique_together': {('event_team', 'group', 'question')},
            },
        ),
    ]
