# Generated by Django 5.2.12 on 2026-03-12 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compforms', '0003_questiongroup_groupquestion_teamquestionassignment'),
        ('events', '0022_alter_team_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='flag_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='flagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuestionSwap',
            fields=[
                ('swap_id', models.AutoField(primary_key=True, serialize=False)),
                ('swapped_at', models.DateTimeField(auto_now_add=True)),
                ('is_flag_driven', models.BooleanField(default=False, help_text='True when swap was triggered by a staff-flagged response. Does not count against team limit.')),
                ('event_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_swaps', to='compforms.eventform')),
                ('event_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_swaps', to='events.eventteam')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='compforms.questiongroup')),
                ('new_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='swapped_in_to', to='compforms.question')),
                ('old_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='swapped_away_from', to='compforms.question')),
                ('swapped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_swaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-swapped_at'],
            },
        ),
    ]
