# Generated by Django 5.2.12 on 2026-03-15 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compforms', '0006_overlayscene_overlaylayout_scene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SHORT_TEXT', 'Short Text'), ('LONG_TEXT', 'Long Text'), ('IMAGE', 'Image Upload'), ('RADIO', 'Radio Select')], default='LONG_TEXT', max_length=20),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='compforms.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
