# Generated by Django 5.2.12 on 2026-03-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compforms', '0008_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SHORT_TEXT', 'Short Text'), ('LONG_TEXT', 'Long Text'), ('IMAGE', 'Image Upload'), ('RADIO', 'Radio Select'), ('MULTI_SELECT', 'Multi Select'), ('TRACTOR_SELECT', 'Tractor Select')], default='LONG_TEXT', max_length=20),
        ),
    ]
