# Generated by Django 5.2.12 on 2026-03-18 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compforms', '0009_alter_question_question_type'),
        ('events', '0022_alter_team_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventform',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventform',
            name='team_class',
            field=models.ForeignKey(blank=True, help_text='Restrict this form to a specific team class. Leave blank to show to all classes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_forms', to='events.teamclass'),
        ),
        migrations.AlterUniqueTogether(
            name='eventform',
            unique_together={('event', 'form', 'team_class')},
        ),
    ]
