# Generated by Django 6.0 on 2025-12-07 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_table_alter_hook_table_alter_pull_table_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='team',
            field=models.OneToOneField(blank=True, db_column='team_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_profile', to='events.team'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_team_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
