# Generated by Django 5.2.10 on 2026-01-23 01:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_groupprofile_team_alter_groupprofile_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('view_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.CharField(max_length=45)),
                ('response_time_s', models.FloatField()),
                ('response_code', models.IntegerField()),
            ],
            options={
                'db_table': 'views',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
