# Generated by Django 5.2.11 on 2026-02-09 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_maneuverabilityrun_teaminfo_tractorinfo_and_more'),
        ('users', '0003_view_alter_groupprofile_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEmail',
            fields=[
                ('team_email_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('collected', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'team_emails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamEnrollmentRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_team_requests', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(db_column='team_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='events.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_enrollment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_enrollment_requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'team'], name='team_enroll_status_2963df_idx'), models.Index(fields=['user', 'team'], name='team_enroll_user_id_b19d39_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'team'), name='unique_pending_request_per_user_team')],
            },
        ),
    ]
