# Generated by Django 5.2.11 on 2026-02-15 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_teamemail_teamenrollmentrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('committee', 'Committee Member'), ('sponsor', 'Sponsor'), ('alumni', 'Alumni'), ('spectator', 'Spectator')], max_length=20)),
                ('school_name', models.CharField(blank=True, default='', max_length=255)),
                ('team_name', models.CharField(blank=True, default='', max_length=255)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('committee_title', models.CharField(blank=True, default='', max_length=255)),
                ('years_on_committee', models.PositiveIntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('sponsorship_level', models.CharField(blank=True, default='', max_length=100)),
                ('alumni_school', models.CharField(blank=True, default='', max_length=255)),
                ('alumni_graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('years_participated', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
