# Generated by Django 5.2.11 on 2026-02-15 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_report'),
        ('users', '0006_userprofile_school_fks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='team_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(blank=True, db_column='team_id_profile', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profiles', to='events.team'),
        ),
    ]
