# Generated by Django 5.2.11 on 2026-02-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userprofile_team_name_userprofile_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='school',
        ),
    ]
