# Generated by Django 5.2.11 on 2026-02-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userprofile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Committee Member'), (3, 'Sponsor'), (4, 'Alumni'), (5, 'Spectator')]),
        ),
    ]
