# Generated by Django 5.2.11 on 2026-02-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='alumni_school',
        ),
    ]
