# Generated by Django 5.2.11 on 2026-02-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_userprofile_alumni_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='committee_title',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='years_on_committee',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Advisor'), (3, 'Sponsor'), (4, 'Alumni'), (5, 'Spectator')]),
        ),
    ]
